### ISSUE TITLE
file not found: data/training.fna

### ISSUE THREAD

**Issue by miferg** [gatech-genemark/ProtHint#42]
Hi,

I am trying to use ProtHint to eventually run GeneMark-EP+ to predict genes in a protist genome following these instructions https://github.com/gatech-genemark/GeneMark-EP-plus. I cloned this repository and then ran the example (../bin/prothint.py input/genome.fasta input/proteins.fasta --geneSeeds input/genemark.gtf --workdir test) which worked without any error and both the test and output evidence files matched. 

Then I tried to actually run prothint with the following command:
`~/mbin/ProtHint/bin/prothint.py ~/protists/test/genomes/assemblies/GYSYB.fna ~/orthodb/obd10_protozoa.faa --workdir ProtHintDir --threads 12`

But I got this error:

`error: Could not find gmes_petap.pl in the PATH`

So I replaced the GeneMarkES empty directory in ProtHint/dependencies/ with a symbolic link to my GeneMarkES installation. Here I have a quick question: Is this correct or am I missing some additional installation instructions?

Now when I am trying to run the same command I am getting the following output:

```
~/mbin/ProtHint/bin/prothint.py ~/protists/test/genomes/assemblies/GYSYB.fna ~/orthodb/obd10_protozoa.faa --workdir ProtHintDir --threads 12
ProtHint Version 2.6.0
Copyright 2019, Georgia Institute of Technology, USA

Please cite
  - ProtHint: https://doi.org/10.1093/nargab/lqaa026
  - DIAMOND:  https://doi.org/10.1038/nmeth.3176
  - Spaln:    https://doi.org/10.1093/bioinformatics/btn460

Called from: /home/miguel/gysyb
Cmd: ../mbin/ProtHint/bin/prothint.py /home/miguel/protists/test/genomes/assemblies/GYSYB.fna /home/miguel/dbs/orthodb/obd10_protozoa.faa --workdir ProtHintDir --threads 12

[Wed Jun 29 18:04:20 2022] Pre-processing protein input
[Wed Jun 29 18:04:24 2022] Running GeneMark-ES.
# check before the run
# hard_mask is in the 'auto' mode. hard_mask was set to: 1000
# creat directories
# commit input data
# warning, PLUS file is empty
# prepare input data report
# commit training data
error, file not found: data/training.fna
[Wed Jun 29 18:04:29 2022] error: ProtHint exited due to an error in command: /home/miguel/mbin/ProtHint/bin/../dependencies/GeneMarkES/gmes_petap.pl --verbose --cores 12 --ES --seq /home/miguel/protists/test/genomes/assemblies/GYSYB.fna --soft auto
```
What could be causing this error?

Thanks in advance. Best
Miguel

**Comment by tomasbruna** [comment]
Hi Miguel,

what happens when you try to run GeneMarkES directly, like this:

    /home/miguel/mbin/ProtHint/bin/../dependencies/GeneMarkES/gmes_petap.pl --verbose --cores 12 --ES --seq /home/miguel/protists/test/genomes/assemblies/GYSYB.fna --soft auto

Also, the latest GeneMark version can run gene prediction supported by ProtHint in a single step, like so: 

    gmes_petap.pl --seq genome.fasta.masked --EP --dbep proteins.fasta --soft_mask auto --cores 8

Best,
Tomas

**Comment by AkshitaJain2709** [comment]
Hi, 
I am getting the similar error as well. 

**Script**
module load ProtHint/2.6.0-iccifort-2019.1.144-GCC-8.2.0-2.31.1-Python-3.7.2
prothint.py /group/pathogens/Akshita/Test_Workflow/Redundans_PE/REDUNDANS_OUT/scaffolds.reduced.fa proteins.fasta

**Output**
ProtHint Version 2.6.0
Copyright 2019, Georgia Institute of Technology, USA

Please cite
  - ProtHint: https://doi.org/10.1093/nargab/lqaa026
  - DIAMOND:  https://doi.org/10.1038/nmeth.3176
  - Spaln:    https://doi.org/10.1093/bioinformatics/btn460

Called from: /group/pathogens/Akshita/Test_Workflow/BRAKER
Cmd: /usr/local/eb/software/generic/ProtHint/2.6.0-iccifort-2019.1.144-GCC-8.2.0-2.31.1-Python-3.7.2/bin/prothint.py /group/pathogens/Akshita/Test_Workflow/Redundans_PE/REDUNDANS_OUT/scaffolds.reduced.fa proteins.fasta
[Fri Aug 19 09:27:39 2022] Pre-processing protein input
[Fri Aug 19 09:27:53 2022] Running GeneMark-ES.
[Fri Aug 19 09:27:53 2022] warning: Could not find gmes_petap.pl in dependencies/GeneMarkES/ folder. Attempting to use gmes_petap.pl in the PATH.
check before run
create directories
commit input data
soft_mask is in the 'auto' mode. soft_mask was set to: 1000
data report
commit training data
training data report
error, file not found: info/training.fna
        (in cleanup)    (in cleanup)  at /usr/local/eb/software/skylake/Perl/5.28.1-GCCcore-8.2.0/lib/perl5/site_perl/5.28.1/Object/InsideOut.pm line 1953 during global destruction.
[Fri Aug 19 09:28:39 2022] **error: ProtHint exited due to an error in command: gmes_petap.pl** --verbose --cores 48 --ES --seq /group/pathogens/Akshita/Test_Workflow/Redundans_PE/REDUNDANS_OUT/scaffolds.reduced.fa --soft auto

What could be causing this error?
Any help is appreciated, Thanks
Akshita

**Comment by tomasbruna** [comment]
Same recommendation - what happens when you run GeneMark separately, i.e.:

      gmes_petap.pl --verbose --cores 48 --ES --seq /group/pathogens/Akshita/Test_Workflow/Redundans_PE/REDUNDANS_OUT/scaffolds.reduced.fa --soft auto

Also, I suspect you are using an older GeneMark version---the "(in cleanup) error" is fixed in the newer versions. If that's the case, please update GeneMark from http://exon.gatech.edu/GeneMark/license_download.cgi.

**Comment by AkshitaJain2709** [comment]
> Same recommendation - what happens when you run GeneMark separately, i.e.:
> 
> ```
>   gmes_petap.pl --verbose --cores 48 --ES --seq /group/pathogens/Akshita/Test_Workflow/Redundans_PE/REDUNDANS_OUT/scaffolds.reduced.fa --soft auto
> ```
> 
> Also, I suspect you are using an older GeneMark version---the "(in cleanup) error" is fixed in the newer versions. If that's the case, please update GeneMark from http://exon.gatech.edu/GeneMark/license_download.cgi.

**Hi, thanks for replying, I installed the latest version for GeneMark, however, I am still getting the same error:**


module purge
module load GeneMark-ET/4.69-GCCcore-8.2.0
gmes_petap.pl --verbose --cores 48 --ES --seq /group/pathogens/Akshita/Test_Workflow/Redundans_PE/REDUNDANS_OUT/scaffolds.reduced.fa --soft auto

check before the run
hard_mask is in the 'auto' mode. hard_mask was set to: 1000
creat directories
commit input data
warning, PLUS file is empty
prepare input data report
commit training data
error, file not found: data/training.fna

Could you please suggest what else can I do. Thanks in advance!

**Comment by tomasbruna** [comment]
How fragmented is your assembly and what is the length of the longest contig in your assembly? I suspect you might be running into a similar issue as described here: https://github.com/Gaius-Augustus/BRAKER/issues/49

Also, what species is this? That might help in debugging as well.

**Comment by AkshitaJain2709** [comment]
Hi Tomas

Thanks for getting back, the longest contig in the assembly is 13541 bp long. I am working with a cyst nematode species, Heterodera mani. However, no reference whole genome sequence is available on NCBI GenBank database.
I am assuming the assembly is quite fragmented although I am not sure how much. 
I want to use ProtHint to generate hints for BRAKER's input for genome annotation.

**Comment by tomasbruna** [comment]
Hi Akshita,

fragmentation is indeed the problem. By default, GeneMark-ES ignores contigs shorter than 50,000 bp in training.

To get around the issue, first run GeneMark-ES separately, with an extra `--min_contig 1000` option. This changes the threshold to 1000 bp.

      gmes_petap.pl --verbose --cores 48 --ES --seq --min_contig scaffolds.reduced.fa --soft auto --min_contig 1000

Next, pass the GeneMark prediction (stored in `genemark.gtf`) to ProtHint as follows:

     prothint.py scaffolds.reduced.fa proteins.fasta --geneSeeds genemark.gtf

Best,
Tomas

**Comment by AkshitaJain2709** [comment]
Hi Tomas 

Thanks for replying, I ran the script as per your recommendation, however, it gives an error as output. 

module purge
module load GeneMark-ET/4.69-GCCcore-8.2.0
gmes_petap.pl --verbose --cores 48 --ES --seq --min_contig 1000 /group/pathogens/Akshita/Test_Workflow/Redundans_PE/REDUNDANS_OUT/scaffolds.reduced.fa --soft auto
error, unexpected argument found on command line: /usr/local/eb/software/generic/GeneMark-ET/4.69-GCCcore-8.2.0/gmes_petap.pl 1000 /group/pathogens/Akshita/Test_Workflow/Redundans_PE/REDUNDANS_OUT/scaffolds.reduced.fa

 gmes_petap.pl --verbose --cores 48 --ES --seq --min_contig /group/pathogens/Akshita/Test_Workflow/Redundans_PE/REDUNDANS_OUT/scaffolds.reduced.fa  --soft auto --mi                                            n_contig 1000
error, unexpected argument found on command line: /usr/local/eb/software/generic/GeneMark-ET/4.69-GCCcore-8.2.0/gmes_petap.pl /group/pathogens/Akshita/Test_Workflow/Redundans_PE/REDUNDANS_OUT/s                                            caffolds.reduced.fa

Regards,
Akshita

**Comment by tomasbruna** [comment]
Sorry, Akshita, there was a typo in my command. Try this:

      gmes_petap.pl --verbose --cores 48 --ES --seq scaffolds.reduced.fa --soft auto --min_contig 1000

**Comment by AkshitaJain2709** [comment]
Hi Tomas

Thankyou so much for your help! Highly appreciate it!!

Regards,
Akshita
